#Take input in two integer variables & perform all bitwise operators using shift operator.
print("----------------------------------------")
print("Name:Ayushi Kapoor")
print("Enrollment No:02417702024")
print("----------------------------------------")
m = int(input("Enter first integer(m): "))
n = int(input("Enter second integer(n): "))
print("\n=== Bitwise Operations ===")
print("Bitwise AND (m & n):", m & n)
print("Bitwise OR (m | n):", m | n)
print("Bitwise XOR (m ^ n):", m ^ n)
print("Bitwise NOT (~m):", ~m)
print("Bitwise Left Shift (m << 1):", m << 1)
print("Bitwise Right Shift (m >> 1):", m >> 1)
print("\n=== Using Shift Operators ===")
print("Left shift m by n (m << n):", m << n)
print("Right shift m by n (m >> n):", m >> n)
